### ISSUE TITLE
Couldn't bootstrap juju controller (mastering tutorial)

### ISSUE THREAD

**Issue by gruyaume** [canonical/charmed-aether-sd-core#64]
### Bug Description

I am getting an lxd error (`/system.slice/lxd-agent.service is not a snap cgroup`) when trying to run any juju command. 

### To Reproduce

1. Follow the mastering tutorial up to the [Prepare the Juju Controller section](https://canonical-charmed-aether-sd-core.readthedocs-hosted.com/en/v1.5/tutorials/mastering/#prepare-the-juju-controller-vm)
2. Run `juju bootstrap microk8s --config controller-service-type=loadbalancer sdcore` 

### Environment

- Ubuntu: 24.04
- Juju: 3.6.0
- Snapd 2.66.1

### Relevant log output

```shell
ubuntu@juju-controller:/$ mkdir -p ~/.local/share/juju
sudo snap install juju --channel=3.6/stable
juju bootstrap microk8s --config controller-service-type=loadbalancer sdcore
juju (3.6/stable) 3.6.0 from Canonical✓ installed
/system.slice/lxd-agent.service is not a snap cgroup
```

```shell
ubuntu@juju-controller:/$ systemctl status lxd-agent.service
● lxd-agent.service - LXD - agent
     Loaded: loaded (/usr/lib/systemd/system/lxd-agent.service; static)
     Active: active (running) since Tue 2024-12-10 19:34:08 UTC; 35min ago
       Docs: https://documentation.ubuntu.com/lxd/en/latest/
   Main PID: 536 (lxd-agent)
      Tasks: 14 (limit: 6541)
     Memory: 195.2M (peak: 216.9M)
        CPU: 12.318s
     CGroup: /system.slice/lxd-agent.service
             ├─  536 /run/lxd_agent/lxd-agent
             ├─37815 bash -l
             ├─44189 systemctl status lxd-agent.service
             └─44190 less

Dec 10 20:05:49 juju-controller sudo[38162]: pam_unix(sudo:session): session closed for user root
Dec 10 20:06:26 juju-controller sudo[39311]:   ubuntu : TTY=pts/0 ; PWD=/ ; USER=root ; COMMAND=/usr/bin/snap install microk8s --channel=1.31-strict/stable
Dec 10 20:06:26 juju-controller sudo[39311]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Dec 10 20:06:26 juju-controller sudo[39311]: pam_unix(sudo:session): session closed for user root
Dec 10 20:06:32 juju-controller sudo[39506]:   ubuntu : TTY=pts/0 ; PWD=/ ; USER=root ; COMMAND=/snap/bin/microk8s config
Dec 10 20:06:32 juju-controller sudo[39506]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Dec 10 20:06:32 juju-controller sudo[39506]: pam_unix(sudo:session): session closed for user root
Dec 10 20:07:18 juju-controller sudo[40708]:   ubuntu : TTY=pts/0 ; PWD=/ ; USER=root ; COMMAND=/usr/bin/snap logs juju
Dec 10 20:07:18 juju-controller sudo[40708]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1000)
Dec 10 20:07:18 juju-controller sudo[40708]: pam_unix(sudo:session): session closed for user root
```

**Comment by gruyaume** [comment]
The issue does not seem to occur with Juju 3.5. Something must have changed between juju 3.5 and 3.6.

**Comment by Gmerold** [comment]
#67 updates the way we log into the LXD machines. This should solve the issue.
@gruyaume I'll close the issue when you confirm the fix.

**Comment by gruyaume** [comment]
This doesn't seem to solve my issue, I'm still getting the same problem using th` su` parameter:

```
ubuntu@juju-controller:/$ lxc exec juju-controller -- su --login ubuntu
Unable to trigger the installation of the LXD snap.
Please make sure you're a member of the 'lxd' system group.
ubuntu@juju-controller:/$ cd /home/ubuntu
export KUBECONFIG=control-plane-cluster.yaml
juju add-k8s control-plane-cluster --controller sdcore
export KUBECONFIG=user-plane-cluster.yaml
juju add-k8s user-plane-cluster --controller sdcore
export KUBECONFIG=gnb-cluster.yaml
juju add-k8s gnb-cluster --controller sdcore
/system.slice/lxd-agent.service is not a snap cgroup
/system.slice/lxd-agent.service is not a snap cgroup
/system.slice/lxd-agent.service is not a snap cgroup

```

**Comment by Gmerold** [comment]
It looks like you're not starting from the host.
`ubuntu@juju-controller:/$ lxc exec juju-controller -- su --login ubuntu` - You're trying to `lxc exec juju-controller` being on `juju-controller`.
